.TH COMPIZ-DECORATOR 1 "October 22, 2011"
.SH NAME
compiz-decorator \- Compiz window decorator
.SH SYNOPSIS
.B compiz-decorator
.RI [ options ]
.SH DESCRIPTION
.B compiz-decorator
is a symlink to gtk-window-decorator.
.SH OPTIONS
.B compiz-decorator
accepts the following options:
.TP
.BI \-\-minimal
Runs only with minimal window decorations.
.TP
.BI \-\-replace
Replaces any running window decorator.
.TP
.BI \-\-help
Prints the list of accepted options.
.SH AUTHOR
gtk-window-decorator was written by David Reveman <davidr@novell.com> and
others.
