.TH bcop 1 "October 22, 2011"
.SH NAME
bcop \- Compiz Fusion option code generator
.SH SYNOPSIS
.B bcop
.RI [ options ]
.SH DESCRIPTION
This tool is used to generate code for use with compiz-fusion plugins.
.SH OPTIONS
.B bcop
accepts the following options:
.TP
.BI \-\-source=<file>
Source file name.
.TP
.BI \-\-header=<file>
Header file name.
.TP
.BI \-\-version
Print version information.
.TP
.BI \-\-help
Display this help message.
.SH AUTHOR
kumattau <kumattau@gmail.com>
